on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'sip3'
          server: 'sip3@ip-69-164-194-46.cloudezapp.io'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './master.ya*'
          remote_path: '/var/www/app'
          args: '-o ConnectTimeout=5'
