name: CD DEPLOY SERINGUEIRAS
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ seringueiras ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: seringueiras3
          server: ip-69-164-194-46.cloudezapp.io
          port: 22122 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /srv/app675.45a4c22e.configr.cloud/www
          
          # sftp args
          args: '-o ConnectTimeout=5'
