name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: 'echo "$SSH_PPK" > the_key'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH_PPK }}
    - name: git-ftp push
      uses: hrsetyono/git-sftp-action@v4
      with:
        url: "sftp://sip.fpstecnologia.com.br/"
        user: ${{ secrets.FTP_USER }}
        password: "@Fsp2011br"
        options: "--key /the_key --auto-init"
